language: erlang
otp_release:
  - 18.1
install:
  - make
  - ./rebar3 update
script:
  - pkill -9 beam.smp; make test
  - make xref
  - make dialyzer
  - make lint
notifications:
  slack: haslab:jhAnACJzswFtYwKXpbZzjbFq
  email: false
sudo: false
