language: erlang
otp_release:
  - 19.3
install:
  - ./rebar3 update
  - make
before_script:
  - epmd -daemon
script:
  - make test
  - make xref
  - make dialyzer
  - make lint
  - make java-client-test
notifications:
  slack: haslab:jhAnACJzswFtYwKXpbZzjbFq
  email: false
sudo: false
